#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := wall.cpp line.cpp ball.cpp circle.cpp window.cpp vector.cpp rectangle.cpp drawable.cpp victim.cpp

# header files in this project
HEADERS := wall.hpp line.hpp ball.hpp circle.hpp window.hpp vector.hpp rectangle.hpp drawable.hpp victim.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.native
